---
# Handlers for common role

- name: restart timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
    daemon_reload: yes

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
